---
version: '2'
services:
  lb:
    image: dockercloud/haproxy
    ports:
      - 8181:80
    networks:
      - front-tier
      - back-tier
  wordpress:
    restart: always
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: cEavYKT4dwcHgqYs
    volumes_from:
      - data
    links:
      - mysql
    networks:
      - back-tier
  mysql:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: cEavYKT4dwcHgqYs
    volumes_from:
      - data
    networks:
      - back-tier
  data:
    image: busybox
    volumes:
      - ./html:/var/www/html
      - ./database:/var/lib/mysql
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge      